name: Keep Render Server Awake

on:
  schedule:
    # Runs every 14 minutes
    - cron: "*/14 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Health Endpoint
        run: curl -s https://pragathi-wellnes-center.onrender.com/api/health
